### ISSUE TITLE
A different take at this

### ISSUE THREAD

**Issue by vitaly-t** [timthesinner/throttle-promised#1]
Would you consider the following approach a suitable alternative for throttling promises? - [Data Throttling & Load Balancing](https://github.com/vitaly-t/spex/blob/master/docs/concept/throttling.md)

I wrote methods [page](https://github.com/vitaly-t/spex/blob/master/docs/code/page.md) and [sequence](https://github.com/vitaly-t/spex/blob/master/docs/code/sequence.md) to provide complete flexibility in how to throttle and balance promise resolution.

**Comment by timthesinner** [comment]
I only notice 2 potential issues with spex.  
1. An easy fix, support array's as a source for page
2. A harder fix, support multiple sources for a sequence
- Perhaps a new construct in your library a way to combine streams?

**Comment by vitaly-t** [comment]
Method `sequence` processes the sequence dynamically, and data can come from any number of sources.

And method `page` accepts arrays of promises/values to process.

Both methods are fully dynamic. An array for `page` as a source would make it a limitation, and thus pointless. What separates it from the limited promise libraries is that it is dynamic.

**Comment by timthesinner** [comment]
I suppose I was not clear:

I suggested adding support to page to accept an array as a source.  I am lazy and don't want to handle this boiler plate myself.

``` JavaScript
if (typeof source === 'array') {//Accept arrays, wrap with promise as a convince
  var _source = source;
  source = $p(function(resolve, reject) { resolve(_source); });
}
if (typeof source !== 'function') {
  throw new TypeError("Invalid page source.");
}
```

Help me understand how one would pass multiple functions through the same sequence?  Let me give an example, I have a client library wrapping all my SOAP access to a vCenter multiple functions (endpoints).  I need to ensure that I only ever have 10 active SOAP requests to the vCenter from my web-service.  To do this I need to throttle each function call through the same sequence.  How can I ensure that only 10 calls are active at one time using sequence?

**Comment by vitaly-t** [comment]
See [sequence + page examples for data throttling](https://github.com/vitaly-t/spex/blob/master/docs/concept/throttling.md).

Your `source` function receives the request index always, you can check it for reaching 10 in your example, and then finish the sequence.

Alternatively, both `page` and `sequence` support option `limit` which you can specify to automatically limit the size of your sequence.

**Comment by vitaly-t** [comment]
Reading again your specific example,... there can be several ways to implement this via `spex`, and here's just one of them:

``` js
var spex = require('spex');

function source(index, data, delay) {
    // return the next promise with SOAP request;
}

function dest(index, data, delay) {
    // another SOAP request has been settled;

    // return a promise here that will resolve once
    // the current queue of requests is less than 10;
}

spex.sequence(source, dest)
    .then(function (data) {
    })
    .catch(function (error) {
    });
```
